Update SauceLabs.mdx
reportportal/docs pull request #539
Opened 2023-03-29 17:56 UTC by lysannep

Updates for readability, also fixes spacing issues.

2023-03-31 08:58 UTC, VolhaKarenko requested changes
Everything is correct, just changed the name of the button

2023-03-31 08:58 UTC, VolhaKarenko commented on docs/plugins/SauceLabs.mdx
> +6. Click Add new integration.
Click 'Add integration'.

2023-03-31 12:07 UTC, pressayuliya commented on docs/plugins/SauceLabs.mdx
> +6. Click Add new integration.
Approved from my side.

2023-03-31 12:07 UTC, pressayuliya commented
Approved from my side.

2023-03-31 18:38 UTC, lysannep commented on docs/plugins/SauceLabs.mdx
> +6. Click Add new integration.
Done.

2023-03-31 18:42 UTC, lysannep commented
Thank you @pressayuliya @VolhaKarenko ~ I added the requested change.

2023-04-03 06:52 UTC, alena-babrova commented
Ok from my side. Approved.

2023-04-03 15:38 UTC, pressayuliya commented
Approved from my side. Thank you.

2023-04-04 14:49 UTC, lysannep commented
> Everything is correct, just changed the name of the button

@VolhaKarenko ~ Can you please approve the PR? I can't merge the changes until I get an official approval.

2023-04-04 14:51 UTC, VolhaKarenko approved these changes
Approved

2023-04-04 14:57 UTC, lysannep commented
@VolhaKarenko Thank you! Can you also merge the PR? I'm not authorized to merge.

2023-04-04 15:00 UTC, VolhaKarenko commented
@AmsterGet please merge the PR

2023-04-04 15:00 UTC, alena-babrova approved these changes

2023-04-04 15:03 UTC, pressayuliya approved these changes

2023-04-04 21:03 UTC, AmsterGet approved these changes

2023-04-04 21:03 UTC, merged